### ISSUE TITLE
Japanese tokeniser and tagger?

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/spacyr#16]
From @koheiw:

> By the way, in order to quickly support multiple languages, we can use online APIs. They are probably not for large scale analysis, but cater to the need of majority of the people.
> I am interested in Rosette. Its POS tagger takes around 0.3 sec for one document in inaugCorpus.  Japanese works fairly well too.
> 
> Kohei
> 
> -------------------------------
> devtools::install_github("hrbrmstr/rosette")
> library(rosette)
> library(quanteda)
> 
> res1 <- ros_morph(texts(inaugCorpus)[[1]])
> res2 <- ros_morph("Original Ghostbuster Dan Aykroyd, who also co-wrote the 1984 Ghostbusters film, couldn’t be more pleased with the new all-female Ghostbusters cast, telling The Hollywood Reporter, 'The Aykroyd family is delighted by this inheritance of the Ghostbusters torch by these most magnificent women in comedy.'")
> 
> res3 <- ros_morph("政治とは社会に対して全体的な影響を及ぼし、社会で生きるひとりひとりの人の人生にも様々な影響を及ぼす複雑な領域である。広辞苑では「人間集団における秩序の形成と解体をめぐって、人が他者に対して、また他者と共に行う営み。」としているわけであるが、政治は、社会や社会に生きるひとりひとりの人にとって そもそも何が重要なことなのか、社会がどのような状態であることが良い状態なのか、ということも扱い、様々ある人々の意志からどれを選び集団の意志とするか、どのような方法でそれを選ぶか、といったこととも深く関係している。")

**Comment by kbenoit** [comment]
From Amy Catalinac:

> The tokenizer is called MeCab [(here)](http://rmecab.jp/wiki/index.php?RMeCab).  It is implemented in R here.  The author and maintainer of the R package is Ishida Motohiro, and his email address is ishida.motohiro@gmail.com.  He's written a guide to its many functions, which can be purchased [here](https://www.amazon.co.jp/dp/4627848412?tag=motohiro-22&camp=243&creative=1615&linkCode=as1&creativeASIN=4627848412&adid=1WR3Y3EW2HQ9P7RR5VM9&).  Somewhere along the way I found a guide to using it in PDF online:
[Manual for RMeCab.pdf](https://github.com/kbenoit/spacyr/files/613388/Manual.for.RMeCab.pdf)
>
> 
> For me to get it to work on my machine, I had to set my OS to Japanese, then download R, so that R is in Japanese.  Then, this code will work.
> 
> library(RMeCab)
> 
> res <- docDF("1986_split", type = 1, N = 1) # reads in files from the folder "1986_split" and makes a TDM
> 
> res2 <- res[res$POS1 %in% c("名詞","形容詞",　"動詞", "副詞") & !(res$POS2 %in% c("代名詞", "非自立")), ] # in the TDM we've just made, keep words classified as nouns, adjectives, verbs, and adverbs, and get rid of words classified as ... etc. etc.
> 
> There is also another tokenizer called Comainu. ...  http://comainu.org/

**Comment by koheiw** [comment]
This is probably the most popular text analysis package in Japan. 
http://khc.sourceforge.net/en/
It is only wrapping Mecab, MySQL, and R.

**Comment by kbenoit** [comment]
Closing this for now, since it's a spaCy issue, not a **spacyr** issue.
