### ISSUE TITLE
problems installing language file in Windows

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/spacyr#19]
Following our own installation instructions, in Windows 10, I was able to install successfully python 2.7 and spaCy. 

However:

```win
C:\Users\kbenoit>python -m spacy.en.download all
C:\Python27\python.exe: DLL load failed: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
```

**Comment by kbenoit** [comment]
And on Windows 7:

```
C:\Python27\python.exe: DLL load failed: The application has failed to start bec
ause its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
```

**Comment by kbenoit** [comment]
@tpaskhalis suggests this issue might be relevant:
https://github.com/explosion/spaCy/issues/830

**Comment by amatsuo** [comment]
It turned out that for running spaCy on Python 2.7 in Windows you need Visual Studio 2008:
https://spacy.io/docs/usage/#source-windows

It's not so easy to find it on microsoft website but the download link is here:
https://www.microsoft.com/en-us/download/details.aspx?id=15336

Once you install it, spaCy should work.

**Comment by tpaskhalis** [comment]
We checked it yesterday with the Visual Studio 2008/Visual C++ Compiler for Python 2.7 installed on both Windows 7 and 10. SpaCy installation itself does work, but not the model downloader. Given this issue, I'd say we should try clean Anaconda installation of Python, NumPy, SciPy, etc.

**Comment by amatsuo** [comment]
It worked in my environment, not sure what the difference between my and your environments. 

The detailed error I got beforehand (from subtrace.exe) was:
```
=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-GB;en;en-US
	ManifestPath = C:\WINDOWS\system32\reg.exe
	AssemblyDirectory = C:\WINDOWS\system32\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\WINDOWS\system32\reg.exe.
	INFO: Manifest Definition Identity is Microsoft.Windows.Filesystem.Reg,processorArchitecture="amd64",type="win32",version="5.1.0.0".
INFO: Activation Context generation succeeded.
End Activation Context Generation.

=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = AMD64
	CultureFallBacks = en-GB;en;en-US
	ManifestPath = C:\Python27\lib\site-packages\spacy\attrs.pyd
	AssemblyDirectory = C:\Python27\lib\site-packages\spacy\
	Application Config File = 
-----------------
INFO: Parsing Manifest File C:\Python27\lib\site-packages\spacy\attrs.pyd.
	INFO: Manifest Definition Identity is (null).
	INFO: Reference: Microsoft.VC90.OpenMP,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8"
INFO: Resolving reference Microsoft.VC90.OpenMP,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8".
	INFO: Resolving reference for ProcessorArchitecture amd64.
		INFO: Resolving reference for culture Neutral.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\WINDOWS\assembly\GAC_64\Microsoft.VC90.OpenMP\9.0.21022.8__1fc8b3b9a1e18e3b\Microsoft.VC90.OpenMP.DLL.
				INFO: Attempt to probe manifest at C:\Python27\lib\site-packages\spacy\Microsoft.VC90.OpenMP.DLL.
				INFO: Attempt to probe manifest at C:\Python27\lib\site-packages\spacy\Microsoft.VC90.OpenMP.MANIFEST.
				INFO: Attempt to probe manifest at C:\Python27\lib\site-packages\spacy\Microsoft.VC90.OpenMP\Microsoft.VC90.OpenMP.DLL.
				INFO: Attempt to probe manifest at C:\Python27\lib\site-packages\spacy\Microsoft.VC90.OpenMP\Microsoft.VC90.OpenMP.MANIFEST.
				INFO: Did not find manifest for culture Neutral.
			INFO: End assembly probing.
	ERROR: Cannot resolve reference Microsoft.VC90.OpenMP,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8".
ERROR: Activation Context generation failed.
End Activation Context Generation.
``` 
By installing Visual Studio 2008 from the link above, it just worked like this:
```
C:\Users\kbenoit>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.en.English()
>>> doc = nlp(u'temp')
>>> doc
temp
```

**Comment by tpaskhalis** [comment]
Do language models get installed without any problem though? SpaCy won't complain if language models aren't available.

**Comment by amatsuo** [comment]
I didn't have any issue downloading it after installing VC. The error pasted by @kbenoit is probably coming from not being able to import the spacy package because of missing dlls.

`python -c "import spacy"` should return the same error.

**Comment by chmue** [comment]
Might the difference be that @kbenoit tried to install it on __32-bit__ Windows and @amatsuo installed it under __64-bit__ Windows?

> spaCy is compatible with __64-bit CPython 2.6+∕3.3+__ and runs on __Unix/Linux__, __macOS/OS X__ and __Windows__.

From [here](https://spacy.io/docs/usage/).

I am currently doing a clean new install on my 64-bit Windows 10 at home and will report back how it goes.

**Comment by amatsuo** [comment]
Not likely. Ken and I are using virtual machines created from the same procedure. 

In any case at the moment, I have some issues with calling spacy from `rstudio/reticulate` which somehow returns errors of missing DLL, which does not happen when I import spacy in console python. I am trying using conda python to see if it will do any better.

**Comment by kbenoit** [comment]
OK, maybe it is an issue with 32-bit VMs in Parallels as @amatsuo and I have.

Can you try installing *spacyr* and seeing if that works?  @amatsuo the `master` contains the Rcpp version, right?

**Comment by amatsuo** [comment]
I believe Rcpp version should not work. I have never been successful in calling python from R, it always complained about missing one or other dll and finally gave up. 

By the way, I finally am able to get the `spacyr` run with `dev_reticulate` with python 3.5. A snapshot of victory is attached.

![screen shot 2017-03-09 at 14 55 43](https://cloud.githubusercontent.com/assets/8436792/23755576/bc2b3734-04d8-11e7-9622-1b189c22d41b.png)

There was a DLL loading error when I tried with python 2.7 with spacy. The error was caused by `reticulate` which failed to load DLL for spacy.

**Comment by chmue** [comment]
> Can you try installing spacyr and seeing if that works?

Apologies for the delay. I took me some time to figure out how to get R to use custom makevars. Here is the output:

```
> writeLines('CPPFLAGS += -I"C:/Users/cm/AppData/Local/Programs/Python/Python36/include"', con = file.path("~", "Makevars"))
> Sys.setenv("R_MAKEVARS_USER" = "~/Makevars")
> devtools::install_github("kbenoit/spacyr")
Downloading GitHub repo kbenoit/spacyr@master
from URL https://api.github.com/repos/kbenoit/spacyr/zipball/master
Installing spacyr
"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/cm/AppData/Local/Temp/RtmpMNMjlG/devtools19874bc22e8/kbenoit-spacyr-461474a"  \
  --library="C:/Users/cm/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'spacyr' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs
C:/RBuildTools/3.4/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG   -I"C:/Users/cm/AppData/Local/Programs/Python/Python36/include"  -I"C:/Users/cm/Documents/R/win-library/3.3/Rcpp/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG   -I"C:/Users/cm/AppData/Local/Programs/Python/Python36/include"  -I"C:/Users/cm/Documents/R/win-library/3.3/Rcpp/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c python.cpp -o python.o
In file included from C:/Users/cm/AppData/Local/Programs/Python/Python36/include/Python.h:8:0,
                 from python.cpp:2:
C:/Users/cm/AppData/Local/Programs/Python/Python36/include/pyconfig.h:61:0: warning: "HAVE_HYPOT" redefined
 #define HAVE_HYPOT
 ^
In file included from C:/Users/cm/Documents/R/win-library/3.3/Rcpp/include/RcppCommon.h:72:0,
                 from C:/Users/cm/Documents/R/win-library/3.3/Rcpp/include/Rcpp.h:27,
                 from python.cpp:1:
C:/PROGRA~1/R/R-33~1.3/include/Rmath.h:64:0: note: this is the location of the previous definition
 # define HAVE_HYPOT 1
 ^
In file included from C:/Users/cm/AppData/Local/Programs/Python/Python36/include/Python.h:8:0,
                 from python.cpp:2:
C:/Users/cm/AppData/Local/Programs/Python/Python36/include/pyconfig.h:327:0: warning: "SIZEOF_SIZE_T" redefined
 # define SIZEOF_SIZE_T 4
 ^
In file included from C:/PROGRA~1/R/R-33~1.3/include/R.h:74:0,
                 from C:/Users/cm/Documents/R/win-library/3.3/Rcpp/include/Rcpp/r/headers.h:52,
                 from C:/Users/cm/Documents/R/win-library/3.3/Rcpp/include/RcppCommon.h:29,
                 from C:/Users/cm/Documents/R/win-library/3.3/Rcpp/include/Rcpp.h:27,
                 from python.cpp:1:
C:/PROGRA~1/R/R-33~1.3/include/Rconfig.h:21:0: note: this is the location of the previous definition
 #define SIZEOF_SIZE_T 8
 ^
python.cpp:6:19: fatal error: dlfcn.h: No such file or directory
 #include <dlfcn.h>
                   ^
compilation terminated.
make: *** [python.o] Error 1
Warning: running command 'make -f "C:/PROGRA~1/R/R-33~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.3/share/make/winshlib.mk" -f "~/Makevars" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="spacyr.dll" WIN=64 TCLBIN=64 OBJECTS="RcppExports.o python.o"' had status 2
ERROR: compilation failed for package 'spacyr'
* removing 'C:/Users/cm/Documents/R/win-library/3.3/spacyr'
Error: Command failed (1)
```

The build fails quite early on because a header file (`dlfcn.h`) is not available. A quick check on my Linux system showed that `dlfcn.h` is installed by GCC. There also seems to be a Windows port (apparently installed by PostgreSQL on my laptop) but this is probably not installed by the default R Windows compiler toolchain.

```
~ % locate dlfcn.h
/usr/include/dlfcn.h
/usr/include/bits/dlfcn.h
/usr/include/postgresql/server/port/win32/dlfcn.h
/usr/share/man/man0/dlfcn.h.0p.gz
~ % pacman -Qo /usr/include/dlfcn.h
/usr/include/dlfcn.h is owned by glibc 2.24-2
```

**Comment by chmue** [comment]
I bit more digging revealed that the Windows "port" of `dlfcn.h` (`/usr/include/postgresql/server/port/win32/dlfcn.h` above) is just an empty file. When I make this empty header available to the spacyr compiler, it throws the error that some of the constants defined in `dlfcn.h` (specifically `RTLD_NOW` and `RTLD_GLOBAL`) are not available ([full log](https://github.com/kbenoit/spacyr/files/831565/spacyr-error-2.txt)).

There seems to be an actual LGPL-licensed port of `dlfcn.h` here: [dlfcn-win32/dlfcn-win32](https://github.com/dlfcn-win32/dlfcn-win32)

**Comment by kbenoit** [comment]
Did you install RTools?

**Comment by amatsuo** [comment]
I have pushed a version of spacyr (`test_win` branch) in windows. With a slight manual setup (see Requirement 2.), it works in my Windows environment. 

Requirement:
1. You need to have `libpython` installed (which is not available python 3.5 in win). 
2. Need to manually create `config.R` because Windows will not create `config.R` from `config.R.in` or `config.R.win` (if you know how to do it, please let me know). 
    - you can create `config.R` by modifying line 3-4 of config.R.win and rename in my environment, it looks like:
       ```
        PYTHON_BIN <- "C:/Users/**/Anaconda2/python.exe"
        PKG_LIBS <- ' -L"C:/Users/**/Anaconda2/python.exe/libs" -lpython27 -DMS_WIN64'
       ```

I tested with anaconda2 and worked. Installing libpython in normal python was not so easy if I remember correctly. 

As I stated above, I am not sure how to auto-generate `config.R` in Windows environment. If you know, please instruct me!

**Comment by kbenoit** [comment]
you can use `cat("config.R text goes here", file = "config.R")`, but you need to get the location first of the python executables to write that.

Please update the installation instructions in `README.Rmd` for this branch, and I will try it. However you might want to merge master into the branch first, since I just accepted the PR that modified that file for the German language model.

**Comment by chmue** [comment]
> I tested with anaconda2 and worked. Installing libpython in normal python was not so easy if I remember correctly.

`%PYTHON_HOME%\libs\libpython36.a` is there in the standard installation (at least for Python 3.6 downloaded from python.org).

> 2. Need to manually create config.R because Windows will not create config.R from config.R.in or config.R.win (if you know how to do it, please let me know).
> 
>     you can create config.R by modifying line 3-4 of config.R.win and rename it to config.R. In my environment, it looks like: 
>     - `PYTHON_BIN <- "C:/Users/**/Anaconda2/python.exe"`
>        `PKG_LIBS <- ' -L"C:/Users/**/Anaconda2/python.exe/libs" -lpython27 -DMS_WIN64'`

This was not necessary as long as the Python executable is in `PATH`.
If the Python executable is not in `PATH`, building fails.

AFAIK, the correct flags are set automatically by [this code](https://github.com/kbenoit/spacyr/blob/temp_win/configure.win#L21-L22).

**Comment by amatsuo** [comment]
Good to know that the package worked. 

> This was not necessary as long as the Python executable is in PATH.
If the Python executable is not in PATH, building fails.
>
> AFAIK, the correct flags are set automatically by this code.

Ya. I know. I wrote `config.win` from the scratch after posted the message above. 

With my changes for `config.win` and `makevars.in`, I believe that installation in Windows is more or less automated once you install `libpython`.

**Comment by chmue** [comment]
Ok! Just ping if you need more testing. I only have the whole pipeline installed on my actual (non-virtualized) Windows machine at home though because Windows Visual Studio alone is 12GB.

**Comment by kbenoit** [comment]
@chmue would be very interested in how the current `master` works for you - we updated this yesterday but are still experiencing some issues.

**Comment by chmue** [comment]
I am terribly sorry to have missed this until now. I overlooked  Here are the results when I try to build the package on x64 R on Windows:
- Building against Python 2: ❎ 
- Building against Python 3: ✅ 

I will update the issue with actual output shortly.

**Comment by chmue** [comment]
I am currently also testing whether calling `spacy_initialize()` also works:

- Built against Python 2: (in progress)
- Built against Python3: 👍 

Python 3 output:

```
PS C:\Users\cm> . 'C:\Program Files\R\R-3.3.3\bin\R.exe' --no-save -q
> library("spacyr")
> spacy_initialize()

    Warning: no model found for 'en'

    Only loading the 'en' tokenizer.

> q()
```

**Comment by chmue** [comment]
Maybe it would make sense to split this new problem with Python 2 into its own issue?

I just did a complete reinstallation of Python 2 and spacy but I might have forgotten to reboot (which might make a difference because it's Windows). So I can investigate this further later and/or tomorrow.

**Comment by kbenoit** [comment]
I just tried this too on a clean Windows 10 VM with Python 2.7. Never got past the spacy installation stage. Following our own instructions (!):

1. Installed [Python 2.7 for Windows](https://www.python.org/downloads/windows/).
2. Installed the [Microsoft Visual C++ Compiler for Python 2.7](http://aka.ms/vcpython27). I restarted Windows after this step.
3. Used `pip` to install spacy:
    ``` bash
    pip install -U spacy
    ```
    As part of this process, it automatically started a dialog box which asked me to install some .NET components, which I did.
4. Got stuck here:
    
```bash
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\kbenoit>pip install libpython
Collecting libpython
  Could not find a version that satisfies the requirement libpython (from versions: )
No matching distribution found for libpython

C:\Users\kbenoit>python -m spacy download en
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Python27\lib\runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "C:\Python27\lib\site-packages\spacy\__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "C:\Python27\lib\site-packages\spacy\deprecated.py", line 8, in <module>
    from .cli import download
  File "C:\Python27\lib\site-packages\spacy\cli\__init__.py", line 5, in <module>
    from .train import train, train_config
  File "C:\Python27\lib\site-packages\spacy\cli\train.py", line 7, in <module>
    from ..scorer import Scorer
  File "C:\Python27\lib\site-packages\spacy\scorer.py", line 4, in <module>
    from .gold import tags_to_entities
ImportError: DLL load failed: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
```

**Comment by chmue** [comment]
Strangely, installing the language model works for me.

```

PS C:\WINDOWS\system32> python -m spacy download en

    Downloading en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz

Collecting https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz (52.2MB)
    100% |################################| 52.2MB 6.8MB/s
Requirement already satisfied: spacy<2.0.0,>=1.7.0 in c:\users\cm\appdata\roaming\python\python27\site-packages (from en-core-web-sm==1.2.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\cm\appdata\roaming\python\python27\site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: six in c:\program files\python27\lib\site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: pathlib in c:\users\cm\appdata\roaming\python\python27\site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: plac<1.0.0,>=0.9.6 in c:\users\cm\appdata\roaming\python\python27\site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: preshed<2.0.0,>=1.0.0 in c:\users\cm\appdata\roaming\python\python27\site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: cymem<1.32,>=1.30 in c:\users\cm\appdata\roaming\python\python27\site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: thinc<6.6.0,>=6.5.0 in c:\users\cm\appdata\roaming\python\python27\site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: numpy>=1.7 in c:\users\cm\appdata\roaming\python\python27\site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: dill<0.3,>=0.2 in c:\users\cm\appdata\roaming\python\python27\site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: regex==2017.4.5 in c:\users\cm\appdata\roaming\python\python27\site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: ujson>=1.35 in c:\users\cm\appdata\roaming\python\python27\site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: murmurhash<0.27,>=0.26 in c:\users\cm\appdata\roaming\python\python27\site-packages (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: cytoolz<0.9,>=0.8 in c:\users\cm\appdata\roaming\python\python27\site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: termcolor in c:\users\cm\appdata\roaming\python\python27\site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: wrapt in c:\users\cm\appdata\roaming\python\python27\site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in c:\users\cm\appdata\roaming\python\python27\site-packages (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: pyreadline>=1.7.1 in c:\users\cm\appdata\roaming\python\python27\site-packages (from dill<0.3,>=0.2->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Requirement already satisfied: toolz>=0.8.0 in c:\users\cm\appdata\roaming\python\python27\site-packages (from cytoolz<0.9,>=0.8->thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
Installing collected packages: en-core-web-sm
  Running setup.py install for en-core-web-sm ... done
Successfully installed en-core-web-sm-1.2.0
symbolic link created for C:\Users\cm\AppData\Roaming\Python\Python27\site-packages\spacy\data\en <<===>> C:\Program Files\Python27\lib\site-packages\en_core_web_sm\en_core_web_sm-1.2.0

    Linking successful

    C:/Program
    Files/Python27/lib/site-packages/en_core_web_sm/en_core_web_sm-1.2.0 -->
    C:/Users/cm/AppData/Roaming/Python/Python27/site-packages/spacy/data/en

    You can now load the model via spacy.load('en').
```

**Comment by kbenoit** [comment]
did you successfully install libpython?

**Comment by chmue** [comment]
I did not try because I don't think I need to install it separately. When you install Python from python.org, the libraries and sources should already be included.

**Comment by leeper** [comment]
@kbenoit The difference between failing at [your step 4](https://github.com/kbenoit/spacyr/issues/19#issuecomment-294937476) and @chmue's [successful `download` command](https://github.com/kbenoit/spacyr/issues/19#issuecomment-294941609) appears to be having Visual C++ 2008 installed [from your link above](https://www.microsoft.com/en-us/download/details.aspx?id=15336) (as opposed to the link in the README which goes nowhere very quickly). I've tracked through the various fixes and cannot get past this point; I don't know python well enough to figure out why this is failing.

**Comment by amatsuo** [comment]
This worked in my brand new Windows (of course it failed in the end). 

1. Install Python2.7 **(Select 64 bit version)**
1. Install VS Express 2008
    - https://go.microsoft.com/fwlink/?LinkId=104679
    - Install "Visual C++ 2008 Express Edition"
1. Install 
    - https://www.microsoft.com/en-us/download/details.aspx?id=44266
1. Install 
    - https://www.microsoft.com/en-us/download/confirmation.aspx?id=15336
1. `pip install -U spacy`
1. `python -m spacy download en`

Following these steps, I managed to get to the error @chmue made in #29

**Comment by amatsuo** [comment]
As @chmue tested, installing with Python 3.6.1 is not so difficult. This is a step-by-step instruction for that:

1. Install Rtools
1. Install Python3.6.1 **Select 64 bit version**
1. Install VS Express 2015
    - https://www.visualstudio.com/post-download-vs/?sku=xdesk&clcid=0x409&telem=ga#
    
1. Install spacy: `pip install -U spacy`
1. Download Language Models: `python -m spacy download en` (you may need to run Command Prompt as an admin, you can get it by right-clicking the windows icon)
1. Install quanteda (not all dependency packages for quanteda are not installed with the installation of spacyr)
1. Install spacyr
 
I will update the documentation of spacyr with these steps.

**Comment by hafez-ahmad** [comment]
ImportError: DLL load failed: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
any solution ? please

**Comment by kbenoit** [comment]
@hafez-ahmad can you provide details about your configuration?
