### ISSUE TITLE
Figure out how to pass Python call through Rcpp

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/spacyr#2]
The current call in https://github.com/kbenoit/spacyr/blob/master/R/tag.R#L71 using `system2()` has a lot of overhead.

Passing directly involves implementing the instructions in http://gallery.rcpp.org/articles/rcpp-python/.

**Comment by adamobeng** [comment]
The linked example uses a list being passed. What should the mapping be between SpaCy data structures and R data structures?

**Comment by kbenoit** [comment]
The return object should be a list of characters or a list of integers if we "hash" these to map to a vocabulary of types. So ideally we could convert a character vector to a list of length one character objects (the texts), pass the reference, and have it update the object to be the list of character tokens (or their integer representation).

The goal is to minimise the transaction cost of passing out of and back into R.

**Comment by tpaskhalis** [comment]
This library for interfacing with `matplotlib` through R has some nice examples of passing objects between R and Python.
https://github.com/mpastell/Rpyplot

**Comment by kbenoit** [comment]
@tpaskhalis Would be great if you could work on tidying up your work in progress so that it passes a full check, and then submitting as PR.

**Comment by tpaskhalis** [comment]
@kbenoit I updated my dev version. No text analysis functionality so far, but it automatically handles python library finding by relying on `configure.ac` script (should work for both Linux and Mac). Passes without errors for me, and a couple of warnings due to lack of documentation.
https://github.com/tpaskhalis/spacyr/tree/dev_rcpp

**Comment by kbenoit** [comment]
@amatsuo will test both approaches, now implemented in `dev_rcpp2`, to see which are compatible with other platforms (Windows mainly!).
