### ISSUE TITLE
Loading spacy does not work on Windows with Python 2.7

### ISSUE THREAD

**Issue by chmue** [kbenoit/spacyr#29]
Split of https://github.com/kbenoit/spacyr/issues/19#issuecomment-294913667

The problem is that on Windows with Python 2.7, loading spacy on the Python command line works but loading spacy via the spacyr package fails:

```
PS C:\Users\cm> . 'C:\Program Files\R\R-3.3.3\bin\R.exe' --no-save -q
> library("spacyr")
> spacy_initialize()
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "C:\Users\cm\AppData\Roaming\Python\Python27\site-packages\spacy\__init__.py", line 5, in <module>
    from .deprecated import resolve_model_name
  File "C:\Users\cm\AppData\Roaming\Python\Python27\site-packages\spacy\deprecated.py", line 8, in <module>
    from .cli import download
  File "C:\Users\cm\AppData\Roaming\Python\Python27\site-packages\spacy\cli\__init__.py", line 5, in <module>
    from .train import train, train_config
  File "C:\Users\cm\AppData\Roaming\Python\Python27\site-packages\spacy\cli\train.py", line 7, in <module>
    from ..scorer import Scorer
  File "C:\Users\cm\AppData\Roaming\Python\Python27\site-packages\spacy\scorer.py", line 4, in <module>
    from .gold import tags_to_entities
ImportError: DLL load failed: The specified module could not be found.
> q()
PS C:\Users\cm> python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.load("en")

    Warning: no model found for 'en'

    Only loading the 'en' tokenizer.

>>> exit()
```

**Comment by chmue** [comment]
I *think* I traced this to a problem with how Python 2.7 and how R (and thus spacyr) link against the Windows C library. The idea to check this comes from [this](https://bugs.python.org/issue16472) bug report.

To reproduce, download DependencyWalker from [here](http://dependencywalker.com/) and inspect `spacyr.dll`.



Python 2.7 (`python27.dll`) links against `msvcr90.dll` whereas the R tools and thus `spacy.dll` links against `msvcrt.dll`.

In the cases of Python 3.6, there is no dependency on `msvcr90.dll` but there is a dependency on `msvcrt.dll` (not on the top level though).

**Comment by chmue** [comment]
Maybe it is be possible to instruct the Rtools compiler to link against `msvcr90.dll` when it detects compilation against Python 2.7?

**Comment by kbenoit** [comment]
Solution: Use 3.6, not 2.7. See new Windows installation instructions.
