### ISSUE TITLE
Fix Travis build failure

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/spacyr#3]
It's failing because spaCy is not installed for Python. Given the size of this object and the required language files, this may not be feasible.

**Comment by kbenoit** [comment]
### Possible solutions

1. install spaCy through a Travis config file 
2. disable the tests for check / build purposes, and donttest all the examples  

I prefer (1) but we would still have the CRAN problem.

**Comment by amatsuo** [comment]
I push a new commit with installing spaCy for travis build (travis_install.sh) . It basically succeeded but still got (seemingly not serious) warnings. In the end I used the option 
```
warnings_are_errors: false
```
in the .travis.yml. Do you think it's enough?

**Comment by kbenoit** [comment]
No, we cannot turn off the warnings I am afraid, but I think I can disable the warnings by excluding the directories that the R build is flagging by specifying them in `.Rbuildignore`. I just pushed such a version and building now.

**Comment by kbenoit** [comment]
Working now, so I am closing this.
