### ISSUE TITLE
Integration with cleanNLP

### ISSUE THREAD

**Issue by statsmaths** [kbenoit/spacyr#32]
At the rOpenSci Text Workshop we discussed how we might combine functionality from [coreNLP](https://github.com/statsmaths/cleanNLP/) into **spacyr**. I'll summarize some of the ideas here so we don't forget them:

- keep cleanNLP as a wrapper around coreNLP, but we should move our combined efforts with spacy into this package
- generally keep the current return format of spacyr, a single data frame, compared to the normalized tables of cleanNLP
- generally switch the backend to the approach of coreNLP, using reticulate and its direct API points; this stops the need to maintain all the complex cpp code and makes it more consistent for users to use different version of Python and spacy models 
- we can try to integrate some of the extra tags I grab or create (i.e., sentence ids) into the output

@amatsuo suggested the best approach would be for him to take the first pass at integrating my approach with reticulate into spacyr, and then I could go back through and submit pull requests to fill in the rough edges.

**Comment by amatsuo** [comment]
@statsmaths 
I have done what I wanted for the new reticulate version. The branch is `dev_reticulate2`. You can check and start working on the additional features.

**Comment by kbenoit** [comment]
Great stuff @amatsuo. I suggest you branch `master` as `spacyr_Rcpp`, and then merge the `dev_reticulate2` into master. Delete the dead branches. Then we will have the old Rcpp version in a fully encapsulated branch, plus the reticulate version.

Or, does the reticulate version still include the option for Rcpp integration?

**Comment by amatsuo** [comment]
`dev_reticulate2` is now merged into `master`. I have already updated the README. So if there are issues with this implementation, we will get feedbacks.

Rcpp is completely removed from the master branch.
