### ISSUE TITLE
travis, testthat

### ISSUE THREAD

**Issue by amatsuo** [kbenoit/spacyr#34]
At the moment, the travis-build fails at a very early stage because suddenly `testthat` cannot be installed. Do you have any idea why?

Here are the lines of logs:
```
Package r-cran-testthat is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'r-cran-testthat' has no installation candidate

The command "eval sudo apt-get install -y r-cran-testthat " failed. Retrying, 2 of 3.
```

https://travis-ci.org/kbenoit/spacyr/builds/225633567#L669

**Comment by kbenoit** [comment]
Something to do with changes in 3.4.0 including some changes to CRAN tests. It's failing on other packages too. Personally I'm waiting to upgrade as I think they were a bit hasty this time between releases and I've been hearing about other problems too! Would not be surprised to see a patch release very soon.

**Comment by amatsuo** [comment]
I suspected so. I will wait for this will be resolved.

**Comment by amatsuo** [comment]
the solution to add `dist: trusty` in `.travis.yml` is causing another issue: the check stops while installing `spacy` (not `spacyr`) even before R installation. I will work on it further.

**Comment by amatsuo** [comment]
After fixing both `.travis.yml` and installation script (`travis_intall.sh`), testthat is working now.
