### ISSUE TITLE
Improvements to spacy_parse()

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/spacyr#44]
### Issue

* some arguments override other arguments, namely `full_parse = TRUE` sets all others to `TRUE`
* the `tagset_*` arguments only apply when `pos_tag = TRUE`
* the argument list could be more "spaCy-like", meaning closer to the Python structure

### Proposal

The new function signature would be:
```r
spacy_parse(x, pos = TRUE, tag = FALSE, lemma = TRUE, entity = TRUE, parse = FALSE)
```
where:
* `pos` means return the [Universal dependencies tagset](http://universaldependencies.org/u/pos/all.html) to which all spaCy language models [must map their tags](https://spacy.io/docs/usage/adding-languages#tag-map)
* `tag` means return the detailed tagset code, which is the [ OntoNotes 5 version of the Penn Treebank tag set](https://spacy.io/docs/usage/pos-tagging#pos-schemes) for the `en` language model, but something different for other languages (e.g. [German](https://spacy.io/docs/usage/pos-tagging#pos-tagging-german)).
* the others are obvious, although `parse` is possibly ambiguous, since it overlaps with the name of this function, while meaning specifically to return the dependency parsing information.

The defaults are set to reflect what most users would want, namely tokenisation and tagging. Tagging is by default the Universal scheme, but the additional details tags can be activated with one argument to change the default. We throw in lemmas for free. Dependency parsing requires one more argument to be specified to override the default.

### Possibly

* rename this function to something more general, such as `spacy_process()`, although I don't like that at all. But the idea would be to find a verb that encompasses all of the activities of tokenizing, tagging, parsing, and extracting NEs.
* an alternative I like less is to separate these functions into `spacy_tokenize()`, `spacy_tag()`, `spacy_parse`, `spacy_getentities()`. These are not even separate steps in the back end.

**Comment by kbenoit** [comment]
@statsmaths would be interested in your opinion on this

**Comment by kbenoit** [comment]
Updated suggestion:
```r
spacy_parse(x, pos = TRUE, tag = FALSE, lemma = TRUE, entity = TRUE, dependency = FALSE)
```

**Comment by statsmaths** [comment]
Just saw this. I generally agree with the structure here. I suppose the only objection to `spacy_parse` is in NLP parse is often synonymous with computing dependencies ("dependency parsing"). `spacy_annotate` probably captures the whole pipeline, but maybe too verbose? However, I personally don't think it is too confusing to just use "parse".

**Comment by kbenoit** [comment]
Thanks @statsmaths. Point taken about "parse". We'd be happy with another more general term but are not sure what it would be. Outside of NLP, "parse" would include things like tokenisation. "Annotate" on the other hand suggests tagging, and not tokenisation.

At the moment "parse" is the weak winner.
