### ISSUE TITLE
Add entity_consolidate()

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/spacyr#45]
The existing function name `get_all_named_entities()` is too long and offers no options. 

Proposal:

* `entity_extract(x, types = c("named", "extended", "all")` - would perform same functionality as  `get_all_named_entities()` but offer just named entities (the first part of the table at https://spacy.io/docs/usage/entity-recognition#entity-types), extended entities (the second part of that table), or all of them.
* `entity_consolidate(spacy_parsed_object, concatenator = "_")` would consolidate the named entities into a single token, replace the sequence with the single concatenated "token", and renumber the token_id within sentence.

**Comment by amatsuo** [comment]
The first point makes sense. 

For the second point, we need to determine the pos tags and dependencies. How do you want to handle it?

**Comment by kbenoit** [comment]
On the second point, I would say that the new "tag" and "pos" become `ENTITY`, and the `named_entity` field becomes the NE type (what it was before concatenation, without the `_B` or `_I`).

**Comment by kbenoit** [comment]
The first part was closed by #48. Now we simply need to implement `entity_consolidate()`.
