### ISSUE TITLE
Strange Results on Windows

### ISSUE THREAD

**Issue by Astelix** [kbenoit/spacyr#56]
Running this job with identical data on my Macbook and on my Windows machine I get completley dfifferent results. I perform the same analysis 100 times on each machine. On OSX I get (as I expected) 100 identical results, in windows I get 100 different results. If I run the same problem on windows in python (same spacy installation) I get the same results as on OSX/R/spacyr.

On both Systems I use R 3.3.3 (Microsoft MRAN) 

```
library(dplyr)
require(spacyr)
require(foreach)

load("MyData.RDATA")
spacy_initialize(condaenv="py36", model="de")


runid <- 0
res <- foreach(i = seq(1,100,1), .combine = "rbind", .errorhandling = "remove") %do% {
  print(i)
  spacy_parse(my_data$text) %>% 
    mutate(runid=i) %>% 
    group_by(runid,pos) %>% 
    summarise(N=n())
}

save(res, file="testruns1.rdata")
tab<-xtabs(N~runid+pos, data=res)
df <- as.data.frame.matrix(mat<-as.matrix(tab))
summary(df)
```

This is sSummary of the OSX and Python/Windows results:

```
ADJ    4937
ADP    6558
ADV    6140
AUX    4091
CONJ   1849
DET    8892
INTJ      2
NOUN  13858
NUM     913
PART   1530
PRON   6088
PROPN  3353
PUNCT 11942
SCONJ   982
SPACE     1
VERB   8134
X       146

```
This is a Summary of R/spacyr/Windows results:

```
     pos   Min   Max  Median
1    ADJ  5286  8045  5477.0
2    ADP  7053 10655  7276.0
3    ADV  6549  9501  6751.0
4    AUX  4351  5905  4450.0
5   CONJ  1978  2744  2032.0
6    DET  9517 13533  9783.0
7   INTJ     1     9     2.0
8   NOUN 14885 21740 15289.0
9    NUM   957  1620   988.0
10  PART  1610  2248  1653.0
11  PRON  6461  8677  6593.0
12 PROPN  3546  5472  3663.5
13 PUNCT 12738 18225 13049.5
14 SCONJ  1051  1424  1084.0
15 SPACE     1     5     1.0
16  VERB  8669 11645  8884.5
17     X   147   273   159.0

```

**Comment by kbenoit** [comment]
Have you checked that the spaCy versions and language models are the same on both platforms? SpaCy has undergone a lot of change recently and depending on when you installed it, you might have different versions.

**Comment by Astelix** [comment]
Yes. The Problem is: The exact same Spacy on Windows gives correct results in Python and wrong results in R. (in environment py36 in Anaconda3/envs). I reinstalled all things on Sunday (OSX) and yesterday (Windows).

**Comment by amatsuo** [comment]
I found this error actually reproducible. Here is a modified code from @Astelix using `quanteda` data. 
```{r}
library(dplyr)
require(spacyr)
require(foreach)
require(quanteda)
require(data.table)

data("data_char_ukimmig2010")
spacy_initialize()

res <- foreach(i = seq(1,100,1), .combine = "rbind", .errorhandling = "remove") %do% {
    print(i)
    spacy_parse(data_char_ukimmig2010) %>% 
        mutate(runid=i) %>% 
        group_by(runid,pos) %>% 
        summarise(N=n())
}

setDT(res)
res[, .(min = min(N), max = max(N)), by = pos][, diff := max - min] %>% print
```
The output from my Mac is:

```
      pos  min  max diff
 1:   ADJ  696  696    0
 2:   ADP  854  854    0
 3:   ADV  244  244    0
 4: CCONJ  263  263    0
 5:   DET  576  576    0
 6:  NOUN 1524 1524    0
 7:   NUM  129  129    0
 8:  PART  181  181    0
 9:  PRON  145  145    0
10: PROPN  421  421    0
11: PUNCT  841  841    0
12: SPACE  185  185    0
13:   SYM    2    2    0
14:  VERB 1114 1114    0
15:     X    1    1    0
```

And from my virtual Windows 10 is like this:
```
 min(N), max = max(N)), by = pos][, diff := max - min] %>% print
      pos  min  max diff
 1:   ADJ  693  801  108
 2:   ADP  854  983  129
 3:   ADV  243  289   46
 4: CCONJ  263  296   33
 5:   DET  576  680  104
 6:  NOUN 1524 1736  212
 7:   NUM  129  157   28
 8:  PART  181  225   44
 9:  PRON  144  152    8
10: PROPN  421  538  117
11: PUNCT  837 1001  164
12: SPACE  185  207   22
13:   SYM    2    2    0
14:  VERB 1114 1356  242
15:     X    1    1    0
```
So there are some issues here. I have some idea why this is happening but need to look into more.

**Comment by kbenoit** [comment]
Let's check first to make sure the results are identical when called through python and not R. Some characters, maybe newlines, could be handled differently, leading to small differences in the results.

**Comment by Astelix** [comment]
The results are not identical. Python on windows produces the same result as R on OSX. Besides this the R results are different for each run with identical input. Could this really be caused by always the same spaces, newlines etc.?

**Comment by kbenoit** [comment]
OK, this suggests there is something indeterminate about the R connection to python using Windows. 

So it sounds like:
- [ ] python spaCy Windows produces identical results to python spaCy macOS
- [ ] python spaCy Windows produces identical results to **spacyr** macOS
- [ ] **spacyr** Windows produces different results from **spacyr** macOS
- [ ] multiple calls to `spacyr::spacy_parse()` Windows produce different results
- [ ] multiple calls to `spacyr::spacy_parse()` macOS produce identical results

Have you confirmed the last?

**Comment by Astelix** [comment]
I called spacy_parse() in a loop 100 times on each system.

 

Von: Kenneth Benoit [mailto:notifications@github.com] 
Gesendet: Donnerstag, 18. Mai 2017 14:19
An: kbenoit/spacyr <spacyr@noreply.github.com>
Cc: Astelix <Thomas.Zapf-Schramm@t-online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [kbenoit/spacyr] Strange Results on Windows (#56)

 

OK, this suggests there is something indeterminate about the R connection to python using Windows.

So it sounds like:

*	[not tested because loading of the model is painfully slow on my notebook] python spaCy Windows produces identical results to python spaCy macOS 
*	[x ] python spaCy Windows produces identical results to spacyr macOS
*	[x ] spacyr Windows produces different results from spacyr macOS
*	[x ] multiple calls to spacyr::spacy_parse() Windows produce different results
*	[x ] multiple calls to spacyr::spacy_parse() macOS produce identical results

Have you confirmed the last?

**Comment by amatsuo** [comment]
@Astelix I pushed new branch "issue56" to the repository. I believe this has fixed the issue, but could you test it? 
```
devtools::install_github("kbenoit/spacyr", ref = "issue56")
```
In my virtual environment, the issue is resolved. I will post what caused the issue in the next comment.

**Comment by amatsuo** [comment]
The problem was the behavior of `time` package in Windows Python. Inside `spacyr`, a parsed document possessed by `spaCy` is identified with the microsecond (not millisecond) level timestamp generated when the document was processed by the `spaCy`. 

https://github.com/kbenoit/spacyr/blob/23b453f27d352bc76c8203fab21a95f135db1385/inst/python/spacyr_class.py#L23

In Mac/Linux this never caused the issue. A line of code above always returns a different value in each call. 

This obviously not the case for windows. I am not sure why this happens, but quite often timestamps are duplicated in Windows. When duplications occur, a previously parsed document by `spaCy` is overwritten by a new document with an identical timestamp. So the output could contain one missing document and one document duplicated in the `spacyr` output.

**Solution:**

A ten-character alpha-numeric string is now attached to the timestamp. This should prevent the duplication.

**Comment by Astelix** [comment]
You fixed it. Great. Thank you very much.
