### ISSUE TITLE
spaCy lemmatization only for English

### ISSUE THREAD

**Issue by bachl** [kbenoit/spacyr#65]
In spaCy, lemmatization is only possible for English texts: https://spacy.io/docs/api/language-models. However, the output of spaCy in Python and, consequently, the output of spacy_parse() does contain something called "lemma" - mostly lower-case versions of the tokens.
Maybe it would make sense to at least issue a warning if language model != english and lemma = TRUE.

**Comment by amatsuo** [comment]
Thanks for the suggestion. 

@kbenoit, there seems to be an ongoing design discussion and development in spaCy on lemmatisation in other language models (or addition user-defined futures to the output. 

https://github.com/explosion/spaCy/issues/1085

As @bachl suggested, adding a warning when the language model is not English would be reasonable. How do you want to proceed with this?

**Comment by kbenoit** [comment]
If lemmas are unavailable when the language model is not English, I'd suggest we eliminate the lemma column from the results for non English language models, and issue a warning if the user manually specifies `lemma = TRUE`.

**Comment by amatsuo** [comment]
That sounds reasonable. I will be on it.
