### ISSUE TITLE
Add progress bar for spacy_parse()?

### ISSUE THREAD

**Issue by stefan-mueller** [kbenoit/spacyr#67]
I was wondering whether we should add a progress bar in the R console when running `spacy_parse()`. Especially for a large corpus POS tagging can take quite a while, so it could be useful to know about the progress. [`txtProgressBar`](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/txtProgressBar.html) is part of base R and might be an easy solution without any package dependencies.

**Comment by kbenoit** [comment]
Not a bad idea, but I doubt that would work with the Python call.

**Comment by stefan-mueller** [comment]
I also expected that the Python call could be a problem, but I thought I just raise this issue. What about printing a warning/info when using `spacy_parse()` that tagging might take a while? Just to make clear to new users that this behaviour is normal.
