### ISSUE TITLE
can spacy_initialize() only execute fully if needed?

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/spacyr#9]
In other words, is there a way to see if a second call to this function needs to be executed, if the connection is already open and working?  Maybe a `force = TRUE` option to override the check, if the user wants it?  (It would be `FALSE` by default.)

Goal: To save time.

**Comment by kbenoit** [comment]
@amatsuo is this implemented? We set `options("spacy_initialized" = TRUE)` in https://github.com/kbenoit/spacyr/blob/master/R/spacy_initialize.R#L18 but I'm not sure if this is checked before the code to initialize a second time is executed.

**Comment by amatsuo** [comment]
This is resolved a while ago.
